routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('makineri', 'Makineri@index');*/


Route::get('atach/{id}', 'MachinesController@atach')->name('atach');
Route::post('update_quantity/{id}', 'MachinesController@update_quantity')->name('update_quantity');
Route::resource('machines','MachinesController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Machines.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Machines extends Model
{
    protected $fillable = [
        'id','name', 'code', 'sasi',
    ];

    public $table ='machines';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MachinesController.php
<?php

namespace App\Http\Controllers;

use App\Machines;
use App\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;



class MachinesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $machines = Machines::where('sasi','!=',0)->paginate(5);

        return view('machines.index',compact('machines'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('machines.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            
            'name' => 'required',
            'code' => 'required',
            'sasi'=> 'required',
        ]);
  
        Machines::create($request->all());
   
        return redirect()->route('machines.index')
                        ->with('success','Machine created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function show(Machines $machine)
    {
        return view('machines.show',compact('machine'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function edit(Machines $machine)
    {    
        if(Auth::user()-> role == "operator"){
            abort('404');
            }

        return view('machines.edit',compact('machine'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function atach($id)
    {    
        if(Auth::user()-> role == "operator"){
            abort('404');
            }
        $clients = User:: where ('role','client')->get();
        $machine = Machines::find($id);

        return view('machines.atach',compact(['clients','machine']));
    }

    public function update_quantity($id){
        $machine = Machines::find($id)->decrement ('sasi');
        
        return redirect()->route('atach',$id)
        ->with('success','Machine atached successfully');
    }

    public function update(Request $request, Machines $machine)
    {
        $request->validate([
            
            'name',
            'code',
            'sasi',
        ]);
  
        $machine->update($request->all());
        if(Auth::user()-> role == "operator"){
            abort('404');
            }
        return redirect()->route('machines.index')
                        ->with('success','Machine updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    
    public function destroy(Machines $machine)
    {
        $machine->delete();

        if(Auth::user()-> role == "operator"){
            abort('404');
            }
        return redirect()->route('machines.index')
                        ->with('success','Machine deleted successfully');
    }
}

app/Http/Controllers/Makineri.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class Makineri extends Controller
{
    function index(){
        return DB::select('SELECT * FROM makinerite');
    }
    
    
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/machines/atach.blade.php
@extends('machines.layout')
   
@section('content')
<form action="{{ route('update_quantity',$machine->id) }}" method="POST">
@csrf 

<select class="form-control m-bot15" name="client">
          @foreach($clients as $client)
           <option value="{{$client->id}}">{{$client->name}}</option>
          @endForeach
            
        </select>

        <button type="submit" value="Submit">Submit</button>

        </form>
    
@endsection

resources/views/machines/create.blade.php
@extends('machines.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Machine</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('machines.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('machines.store') }}" method="POST">
    @csrf
  
     <div class="row">
     
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Code:</strong>
                <input type="text" name="code" class="form-control" placeholder="code">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sasi:</strong>
                <input type="text" name="sasi" class="form-control" placeholder="sasi">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/machines/edit.blade.php
@extends('machines.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Machine</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('machines.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('machines.update',$machine->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $machine->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Code:</strong>
                    <input type="text" name="Code" value="{{ $machine->code }}" class="form-control" placeholder="Code">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/machines/index.blade.php
@extends('machines.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Disinfectant Machinery</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('machines.create') }}"> Create New Machine</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Code</th>
            <th>Sasi</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($machines as $machine)
        <tr>
            <td>{{ ++$i }}</td>
            
            <td>{{ $machine->name }}</td>
            <td>{{ $machine->code }}</td>
            <td>{{ $machine->sasi }}</td>

            <td>
                <form action="{{ route('machines.destroy',$machine->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('machines.show',$machine->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('machines.edit',$machine->id) }}">Edit</a>
                    <a class="btn btn-primary" href="{{ route('atach',$machine->id) }}">Atach</a>

                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Sure Want Delete?')">Delete</button>
                
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $machines->links() !!}
      
@endsection

resources/views/machines/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Disinfectant Machinery</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

resources/views/machines/show.blade.php
 @extends('machines.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Machine</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('machines.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $machine->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Code:</strong>
                {{ $machine->code }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sasi:</strong>
                {{ $machine->sasi }}
            </div>
        </div>
    </div>
@endsection 